### ISSUE TITLE
Pytest 6.1 compatibility

### ISSUE THREAD

**Issue by last-partizan** [theY4Kman/pytest-lambda#3]
Hi

Is there something preventing this plugin from working with pytest 6.1?

**Comment by theY4Kman** [comment]
Nope, I've just been a little zealous in keeping the version pins limited to ensure compatibility. I'm open to being more permissive with the pins (like, allowing all of a major version) — but for now, I've added 6.1 to the tox tests and updated the pin to `pytest<6.2`; it's up on PyPI as version 1.2.1.
